checks:
  javascript: true
build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run

  coverage:
    tests:
      override:
        - command: 'yarn test'
          coverage:
            file: coverage/clover.xml
            # These formats are supported:
            # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
            format: clover
