version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      — image: circleci/node:7.10
    steps:
      — checkout
      - run:
          name: 'Install dependencies'
          command: 'npm install'
